# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'Example' do
  use_frameworks!

  pod 'RxSwift', :inhibit_warnings => true
  pod 'RxCocoa', :inhibit_warnings => true

end
